{% set name = "cf-python" %}
{% set version = "3.18.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: fa80b9499d433902bd2d093700ef2c76ab6541f501a393b2135f0c032d824e45
  patches:
    - 0001-Fix-gcc_path-umread_lib-linux.patch  # [linux]

build:
  number: 1
  skip: true  # [win or py<311]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make
  host:
    - python
    - setuptools
    - pip
  run:
    - distributed >=2025.5.1
    - python
    - netcdf4 ==1.7.2
    - cftime >=1.6.4
    - numpy >=2.0.0
    - cfdm >=1.12.3.1,<1.12.4.0
    - psutil >=0.6.0
    - cfunits >=3.3.7
    - dask-core >=2025.5.1
    - packaging >=20.0
    - scipy >=1.10.0
    - h5netcdf >=1.3.0
    - h5py >=3.10.0
    - s3fs >=2024.6.0

test:
  source_files:
    - cf/test/
  imports:
    - cf
  commands:
    - pip check
    - pushd cf/test && python create_test_files.py && python setup_create_field.py && python -c "import unittest; from cf.test import test_pp; unittest.main(test_pp)"
  requires:
    - pip
    - pytest
    - pycodestyle
    - esmpy
    - mpich
    - pytest-json-report
    - scipy

about:
  home: https://pypi.org/project/cf-python/
  summary: A CF-compliant earth science data analysis library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
