{% set name = "cf-python" %}
{% set version = "3.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e6784cd21f5a7551791b5b0511a8d96710ac23966b6425a73adc9425eac53e8a

build:
  number: 1
  skip: true  # [win or py<35]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - python
    - pip
  run:
    - python
    - cfdm >=1.8.7.0,<1.8.8.0
    - cftime >=1.2.1
    - cfunits >=3.3.0
    - netcdf4 >=1.5.3
    - numpy >=1.15
    - psutil >=0.6.0

test:
  imports:
    - cf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/cf-python/
  summary: A CF-compliant earth science data analysis library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
