{% set name = "cf-python" %}
{% set version = "3.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fae4fb7f3daf11d5b8c10a8ff2e5709e430564bb25714ac1a75313624dffed03

build:
  number: 0
  skip: true  # [win or py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - python
    - pip
  run:
    - python
    - cfdm >=1.8.5,<1.9
    - cftime >=1.1.3
    - cfunits >=3.2.7
    - netcdf4 >=1.5.3
    - numpy >=1.15
    - psutil >=0.6.0

test:
  imports:
    - cf
    - cf.abstract
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/cf-python/
  summary: A CF-compliant earth science data analysis library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
