{% set name = "cf-python" %}
{% set version = "3.13.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8d7f82a9563c0ae46c2725faeca43ee3a2db12a9b75c5a819bcb1b5ef107f322

build:
  number: 0
  skip: true  # [win or py<35]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - cfdm
    - cftime
    - cfunits
    - netcdf4
    - netcdf-flattener
    - numpy
    - psutil
    - packaging
    - pyparsing
  host:
    - python
    - pip
  run:
    - python
    - cfdm 
    - cftime 
    - cfunits 
    - netcdf4 
    - numpy 
    - psutil 

test:
  imports:
    - cf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/cf-python/
  summary: A CF-compliant earth science data analysis library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
