{% set name = "cf-python" %}
{% set version = "3.13.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8af57ea299afd3986a2dbb829524afce07d1e0c8c977702394bf10fbefb22821
  patches:
    - 0001-Fix-gcc_path-umread_lib-linux.patch  # [linux]

build:
  number: 0
  skip: true  # [win or py<35]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - python
    - pip
  run:
    - python
    - cfdm >=1.9.0.4,<1.9.1.0
    - cftime >=1.5.0
    - cfunits >=3.3.4
    - netcdf4 >=1.5.4
    - numpy >=1.15
    - psutil >=0.6.0
    - packaging >=20.0

test:
  imports:
    - cf
  commands:
    - pip check
    - python -c "import unittest; from cf.test import test_pp; unittest.main(test_pp)"
  requires:
    - pip

about:
  home: https://pypi.org/project/cf-python/
  summary: A CF-compliant earth science data analysis library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
