{% set name = "cf-python" %}
{% set version = "3.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2c769f73d52ad99587aac7672a96e94e158a66565b73db7cfad5f777f487bcb3

build:
  number: 1
  skip: true  # [win or py<35]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - python
    - pip
  run:
    - python
    - cfdm >=1.8.8.0,<1.8.9.0
    - cftime >=1.3.0
    - cfunits >=3.3.1
    - netcdf4 >=1.5.3
    - numpy >=1.15
    - psutil >=0.6.0

test:
  imports:
    - cf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/cf-python/
  summary: A CF-compliant earth science data analysis library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
