{% set name = "cf-python" %}
{% set version = "3.16.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: be3e6e79cc1a21a0b5c6a259087ee63ae0e39e0adbeee662cf8a6c079c597d49
  patches:
    - 0001-Fix-gcc_path-umread_lib-linux.patch  # [linux]

build:
  number: 1
  skip: true  # [win or py<35]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make
  host:
    - python
    - setuptools
    - pip
  run:
    - scipy >=1.10.0
    - python
    - netcdf4 >=1.6.5
    - cftime >=1.6.2
    - numpy >=1.22
    - cfdm >=1.11.1.0,<1.11.2.0
    - psutil >=0.6.0
    - cfunits >=3.3.7
    - dask-core >=2022.12.1
    - packaging >=20.0

test:
  source_files:
    - cf/test/
  imports:
    - cf
  commands:
    - pip check
    - pushd cf/test && python create_test_files.py && python setup_create_field.py && python -c "import unittest; from cf.test import test_pp; unittest.main(test_pp)"
  requires:
    - pip
    - pytest
    - pycodestyle
    - esmpy
    - mpich
    - pytest-json-report
    - scipy

about:
  home: https://pypi.org/project/cf-python/
  summary: A CF-compliant earth science data analysis library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
