{% set name = "cf-python" %}
{% set version = "3.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7749fd6b554fd1d2d4ef6b458ca2bd56d0eae2d7d180f6c6a0e95e1873f59db8

build:
  number: 0
  skip: true  # [win or py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - python
    - pip
  run:
    - python
    - cfdm ==1.8.3
    - cftime >=1.1.1
    - cfunits >=3.2.5
    - netcdf4 >=1.5.3
    - numpy >=1.15
    - psutil >=0.6.0

test:
  imports:
    - cf
    - cf.abstract
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/cf-python/
  summary: A CF-compliant earth science data analysis library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
