{% set name = "cf-python" %}
{% set version = "3.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3edae69467be1fe1ebdc8b615e30dd8b437bc79dc0cfb17dbb9da97a9e412288

build:
  number: 1
  skip: true  # [win or py<35]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - python
    - pip
  run:
    - python
    - cfdm >=1.9.0.0,<1.9.1.0
    - cftime >=1.5.0
    - cfunits >=3.3.3
    - netcdf4 >=1.5.4
    - numpy >=1.15
    - psutil >=0.6.0

test:
  imports:
    - cf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/cf-python/
  summary: A CF-compliant earth science data analysis library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
