{% set name = "cf-python" %}
{% set version = "3.14.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4d93e28c8bbe06ae51856e476b15563ea528a75f7d266eec73ed8d8c2e027fb9
  patches:
    - 0001-Fix-gcc_path-umread_lib-linux.patch  # [linux]

build:
  number: 1
  skip: true  # [win or py<35]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - python
    - pip
  run:
    - python
    - netcdf4 >=1.5.4
    - cftime >=1.6.0
    - numpy >=1.22
    - cfdm >=1.10.0.2,<1.10.1.0
    - psutil >=0.6.0
    - cfunits >=3.3.4
    - dask-core >=3.3.4
    - packaging >=20.0

test:
  source_files:
    - cf/test/
  imports:
    - cf
  commands:
    - pip check
    - pushd cf/test && python create_test_files.py && python setup_create_field.py && python -c "import unittest; from cf.test import test_pp; unittest.main(test_pp)"
  requires:
    - pip
    - pytest
    - pycodestyle
    - esmpy
    - mpich
    - pytest-json-report
    - scipy

about:
  home: https://pypi.org/project/cf-python/
  summary: A CF-compliant earth science data analysis library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
